### ISSUE TITLE
Not getting device name in scan ?

### ISSUE THREAD

**Issue by thekundankamal** [theappbusiness/Tracy#3]
Hello, 
I am always getting null in device name how can I get it.

**Comment by KaneCheshire** [comment]
You need to include the local name in the advertisement data on the device that is advertising, but for a contact tracing app you shouldn't need to capture the device name. Advertisement data can only contain a limited amount of data, which you can easily fill if you include the device name, since you'll also need to include the service UUID in the advertisement data. 

If you go over the maximum data size both platforms will fail advertising, and on iOS advertisement performance can be degraded in the background if multiple apps are advertising at the same time and using lots of data.

Additionally, the larger the data, the longer it can take to have a scan result, so really think whether including the name is a requirement (you might not be able to include the full name if it takes up too much data).

You can find out more about the advertisement data structure in the [iOS](https://developer.apple.com/documentation/corebluetooth/cbperipheralmanager/1393252-startadvertising) and [Android](https://developer.android.com/reference/android/bluetooth/le/BluetoothLeAdvertiser) developer docs, [Bluetooth specifications](https://www.bluetooth.com/specifications/assigned-numbers/generic-access-profile/) and also I did some [reverse engineering](https://github.com/KaneCheshire/remotely) of a Boosted board remote control which explains how to interrogate the raw data.

It's important to remember that Android gives you more control than iOS does over what is advertised, and when. On iOS, Apple only give you 28 bytes to advertise with while in the foreground, and less in the background, Android give you the full 31 bytes (62 bytes including scan response) so you have more to work with.
